table complaints
	lineageTag: d36af046-b8f4-4360-b5f4-dc3e75638281

	column complaint_id
		dataType: string
		lineageTag: c3275619-4720-41e5-916e-d11819f91ad2
		summarizeBy: none
		sourceColumn: complaint_id

	column customer_id
		dataType: string
		lineageTag: a0b32ccd-0726-481e-9e36-b14bb65d22f2
		summarizeBy: none
		sourceColumn: customer_id

	column complaint_date
		dataType: dateTime
		formatString: dd MMM yyyy
		lineageTag: 6b3238a4-6bce-4942-8103-a66c3261721f
		summarizeBy: none
		sourceColumn: complaint_date

		annotation UnderlyingDateTimeDataType = Date

	column category
		dataType: string
		lineageTag: a795d94a-1f50-47a3-b0ca-bcb7796f7826
		summarizeBy: none
		sourceColumn: category

	column resolution_time_hours
		dataType: int64
		lineageTag: 17de0705-1533-4fe2-952f-dae9745dd7bc
		summarizeBy: none
		sourceColumn: resolution_time_hours

	partition complaints = m
		mode: import
		source =
				let
				 Source = Csv.Document(File.Contents("C:\Users\Admin\Documents\Network Congestion and Churn analysis\dashboard\OLT_Professional_Project\data\complaints.csv"),[Delimiter=",",Encoding=65001,QuoteStyle=QuoteStyle.Csv]),
				 Headers = Table.PromoteHeaders(Source,[PromoteAllScalars=true]),
				 Typed = Table.TransformColumnTypes(Headers,{{"complaint_id", type text},{"customer_id", type text},{"complaint_date", type date},{"category", type text},{"resolution_time_hours", Int64.Type}},"en-US")
				in Typed

