table customers_clean
	lineageTag: af7907cd-2c38-41fd-a3ec-a0f3da346e77

	column customer_id
		dataType: string
		lineageTag: 8c639677-9c6a-4224-a0bd-a623d6cd38dc
		summarizeBy: none
		sourceColumn: customer_id

	column plan_id
		dataType: int64
		lineageTag: 81489cd1-97c9-4992-b994-4ff8f3588df3
		summarizeBy: none
		sourceColumn: plan_id

	column olt_id
		dataType: int64
		lineageTag: 23e3afa3-969e-4429-935b-270d62edc9ec
		summarizeBy: none
		sourceColumn: olt_id

	column activation_date
		dataType: dateTime
		formatString: dd MMM yyyy
		lineageTag: 5f4b5d4f-7133-466c-bed0-1be5b5c2630a
		summarizeBy: none
		sourceColumn: activation_date

		annotation UnderlyingDateTimeDataType = Date

	column status
		dataType: string
		lineageTag: f7324e0c-96a0-4e46-a200-1e110939638a
		summarizeBy: none
		sourceColumn: status

	column customer_type
		dataType: string
		lineageTag: 3d9232e8-c083-4f68-8dc1-1ee8e3a98859
		summarizeBy: none
		sourceColumn: customer_type

	column connection_count_per_customer
		dataType: int64
		lineageTag: 56c7416f-2915-4459-a159-9205bd45e017
		summarizeBy: none
		sourceColumn: connection_count_per_customer

	column plan_tier
		dataType: string
		lineageTag: 0a879334-4a9d-43da-8652-969a9ef498a9
		summarizeBy: none
		sourceColumn: plan_tier

	column value_segment
		dataType: string
		lineageTag: bb536720-2351-4b81-977e-809057e46575
		summarizeBy: none
		sourceColumn: value_segment

	column area
		dataType: string
		lineageTag: a118676c-7a7d-4a46-a584-513c87a11ed6
		summarizeBy: none
		sourceColumn: area

	column legacy_prepared_future_activation_flag
		dataType: int64
		lineageTag: 78c9a1a0-6554-4c89-95f4-a077be153905
		summarizeBy: none
		sourceColumn: legacy_prepared_future_activation_flag

	column activation_date_withheld_flag
		dataType: int64
		lineageTag: 01230848-97c2-49cf-aa15-5100a3089bce
		summarizeBy: none
		sourceColumn: activation_date_withheld_flag

	partition customers_clean = m
		mode: import
		source =
				let
				 Source = Csv.Document(File.Contents(DataRoot & "customers_clean.csv"),[Delimiter=",",Encoding=65001,QuoteStyle=QuoteStyle.Csv]),
				 Headers = Table.PromoteHeaders(Source,[PromoteAllScalars=true]),
				 Nulls = Table.ReplaceValue(Headers,"",null,Replacer.ReplaceValue,Table.ColumnNames(Headers)),
				 Typed = Table.TransformColumnTypes(Nulls,{{"customer_id", type text},{"plan_id", Int64.Type},{"olt_id", Int64.Type},{"activation_date", type date},{"status", type text},{"customer_type", type text},{"connection_count_per_customer", Int64.Type},{"plan_tier", type text},{"value_segment", type text},{"area", type text},{"legacy_prepared_future_activation_flag", Int64.Type},{"activation_date_withheld_flag", Int64.Type}},"en-US")
				in Typed

