table customer_daily_metrics
	lineageTag: 5ecbfbcc-13a4-4b56-b91c-29b28527f0af

	column customer_id
		dataType: string
		lineageTag: 0d77e91a-71be-48ba-977e-b953f3f99723
		summarizeBy: none
		sourceColumn: customer_id

	column olt_id
		dataType: int64
		lineageTag: 4919c793-c064-4a7a-92f7-dd2927114807
		summarizeBy: none
		sourceColumn: olt_id

	column log_date
		dataType: dateTime
		formatString: dd MMM yyyy
		lineageTag: fe60efab-933a-4905-a442-6d0946ae63eb
		summarizeBy: none
		sourceColumn: log_date

		annotation UnderlyingDateTimeDataType = Date

	column plan_tier
		dataType: string
		lineageTag: 2393c172-31a9-421c-b73d-d97e99a25f78
		summarizeBy: none
		sourceColumn: plan_tier

	column value_segment
		dataType: string
		lineageTag: e802c5f9-7813-4400-a7c6-3859185b8cf6
		summarizeBy: none
		sourceColumn: value_segment

	column data_usage_gb
		dataType: int64
		lineageTag: 0053c340-73a0-4dd3-a89a-4795b3442aba
		summarizeBy: none
		sourceColumn: data_usage_gb

	column avg_speed_mbps
		dataType: int64
		lineageTag: affd9ba1-84da-4cc3-84e3-cbe2d85c53ab
		summarizeBy: none
		sourceColumn: avg_speed_mbps

	column downtime_minutes
		dataType: int64
		lineageTag: 7df76fe5-6373-4b5d-b757-78872487870a
		summarizeBy: none
		sourceColumn: downtime_minutes

	column latency_ms
		dataType: int64
		lineageTag: 33e82a9a-8bec-4550-9003-951d0b58d6d1
		summarizeBy: none
		sourceColumn: latency_ms

	column speed_score
		dataType: int64
		lineageTag: 5809ffdb-8db7-491f-b80e-88de0e877d63
		summarizeBy: none
		sourceColumn: speed_score

	column downtime_score
		dataType: int64
		lineageTag: b3591c8d-0ac2-4c39-bcbc-6337ec15baa9
		summarizeBy: none
		sourceColumn: downtime_score

	column latency_score
		dataType: int64
		lineageTag: 8592d017-8776-49e4-90e3-2747103ea650
		summarizeBy: none
		sourceColumn: latency_score

	column experience_score
		dataType: double
		lineageTag: 1f54f010-4bf7-4113-8d70-a56a3321a4c8
		summarizeBy: none
		sourceColumn: experience_score

	column current_7d_avg
		dataType: double
		lineageTag: 965de13f-2030-45b6-b998-695b40a5a208
		summarizeBy: none
		sourceColumn: current_7d_avg

	column previous_7d_avg
		dataType: double
		lineageTag: cd6d29b9-70e6-4d5b-8d53-e456f344a776
		summarizeBy: none
		sourceColumn: previous_7d_avg

	column complaint_count
		dataType: int64
		lineageTag: 6ef25889-9345-4881-89bc-2dac84351a38
		summarizeBy: none
		sourceColumn: complaint_count

	column complaint_count_30d
		dataType: int64
		lineageTag: 0bfe6cd2-e346-4f01-aa76-264ab2f4ec6d
		summarizeBy: none
		sourceColumn: complaint_count_30d

	column usage_drop_percent
		dataType: double
		lineageTag: 2586dc38-6e57-4cf8-9326-3bb59e1ffc75
		summarizeBy: none
		sourceColumn: usage_drop_percent

	column usage_window_complete
		dataType: boolean
		lineageTag: 54c7bf7e-7784-4a5a-af7c-27b3eb428ccd
		summarizeBy: none
		sourceColumn: usage_window_complete

	column high_usage_drop_flag
		dataType: int64
		lineageTag: 8a6940fb-27e4-4f4e-9c96-3a072ed4275f
		summarizeBy: none
		sourceColumn: high_usage_drop_flag

	column high_downtime_flag
		dataType: int64
		lineageTag: 85ebce3e-3949-4fa1-9c88-f7b9ec253f21
		summarizeBy: none
		sourceColumn: high_downtime_flag

	column high_latency_flag
		dataType: int64
		lineageTag: 1732ed38-20fe-4459-b4f9-597a9a6a329e
		summarizeBy: none
		sourceColumn: high_latency_flag

	column low_experience_flag
		dataType: int64
		lineageTag: 94ce9d76-6624-4f2b-aea5-037d7888cb7f
		summarizeBy: none
		sourceColumn: low_experience_flag

	column complaint_leakage_flag
		dataType: int64
		lineageTag: cbdf33f8-4f32-4f81-803a-8269bc902117
		summarizeBy: none
		sourceColumn: complaint_leakage_flag

	column risk_observed_component_score
		dataType: int64
		lineageTag: e8978a47-819c-44f8-bd63-4649aa401f57
		summarizeBy: none
		sourceColumn: risk_observed_component_score

	column churn_risk_score
		dataType: double
		lineageTag: f469a12e-b68f-4d95-b60e-f1ee3796b3f5
		summarizeBy: none
		sourceColumn: churn_risk_score

	column churn_risk_category
		dataType: string
		lineageTag: d4ac6bdb-9664-40a3-8d9d-d4bae0509cfc
		summarizeBy: none
		sourceColumn: churn_risk_category

	partition customer_daily_metrics = m
		mode: import
		source =
				let
				 Source = Csv.Document(File.Contents(DataRoot & "customer_daily_metrics.csv"),[Delimiter=",",Encoding=65001,QuoteStyle=QuoteStyle.Csv]),
				 Headers = Table.PromoteHeaders(Source,[PromoteAllScalars=true]),
				 Nulls = Table.ReplaceValue(Headers,"",null,Replacer.ReplaceValue,Table.ColumnNames(Headers)),
				 Typed = Table.TransformColumnTypes(Nulls,{{"customer_id", type text},{"olt_id", Int64.Type},{"log_date", type date},{"plan_tier", type text},{"value_segment", type text},{"data_usage_gb", Int64.Type},{"avg_speed_mbps", Int64.Type},{"downtime_minutes", Int64.Type},{"latency_ms", Int64.Type},{"speed_score", Int64.Type},{"downtime_score", Int64.Type},{"latency_score", Int64.Type},{"experience_score", type number},{"current_7d_avg", type number},{"previous_7d_avg", type number},{"complaint_count", Int64.Type},{"complaint_count_30d", Int64.Type},{"usage_drop_percent", type number},{"usage_window_complete", type logical},{"high_usage_drop_flag", Int64.Type},{"high_downtime_flag", Int64.Type},{"high_latency_flag", Int64.Type},{"low_experience_flag", Int64.Type},{"complaint_leakage_flag", Int64.Type},{"risk_observed_component_score", Int64.Type},{"churn_risk_score", type number},{"churn_risk_category", type text}},"en-US")
				in Typed

