table olt_daily_metrics
	lineageTag: 92a2231d-94f4-4c5a-a689-711a509d7cfe

	column olt_id
		dataType: int64
		lineageTag: 7fa162b4-4dd8-40ad-8ff5-cc7c5a331794
		summarizeBy: none
		sourceColumn: olt_id

	column log_date
		dataType: dateTime
		formatString: dd MMM yyyy
		lineageTag: 00651ca1-215b-4094-ba2b-85653ad8f206
		summarizeBy: none
		sourceColumn: log_date

		annotation UnderlyingDateTimeDataType = Date

	column total_usage_gb
		dataType: int64
		lineageTag: 0662d828-87d3-4c64-bf86-d3b56290978c
		summarizeBy: none
		sourceColumn: total_usage_gb

	column capacity_gbps
		dataType: int64
		lineageTag: 49e302d0-b95f-42f9-b635-e16a6b2bb57a
		summarizeBy: none
		sourceColumn: capacity_gbps

	column avg_gbps
		dataType: double
		lineageTag: d61a1a1a-f0ab-4c5a-a585-5b07707aa816
		summarizeBy: none
		sourceColumn: avg_gbps

	column congestion_ratio
		dataType: double
		lineageTag: 8f888dc4-e79e-460b-bd4c-996344621bd1
		summarizeBy: none
		sourceColumn: congestion_ratio

	column congestion_ratio_percent
		dataType: double
		lineageTag: 9b3abe29-7e41-44cc-88ab-b32465c1093a
		summarizeBy: none
		sourceColumn: congestion_ratio_percent

	column congestion_status
		dataType: string
		lineageTag: 0f763aa5-174f-4ae5-93f4-92d31fa01207
		summarizeBy: none
		sourceColumn: congestion_status

	partition olt_daily_metrics = m
		mode: import
		source =
				let
				 Source = Csv.Document(File.Contents(DataRoot & "olt_daily_metrics.csv"),[Delimiter=",",Encoding=65001,QuoteStyle=QuoteStyle.Csv]),
				 Headers = Table.PromoteHeaders(Source,[PromoteAllScalars=true]),
				 Nulls = Table.ReplaceValue(Headers,"",null,Replacer.ReplaceValue,Table.ColumnNames(Headers)),
				 Typed = Table.TransformColumnTypes(Nulls,{{"olt_id", Int64.Type},{"log_date", type date},{"total_usage_gb", Int64.Type},{"capacity_gbps", Int64.Type},{"avg_gbps", type number},{"congestion_ratio", type number},{"congestion_ratio_percent", type number},{"congestion_status", type text}},"en-US")
				in Typed

