table olt_info_clean
	lineageTag: f4acab30-2a12-487f-8656-d4246670b139

	column olt_id
		dataType: int64
		lineageTag: 6170a663-273b-4c79-9527-b339130f6d48
		summarizeBy: none
		sourceColumn: olt_id

	column olt_name
		dataType: string
		lineageTag: 672a12ac-5341-42b0-8072-929e5500bba8
		summarizeBy: none
		sourceColumn: olt_name

	column capacity_gbps
		dataType: int64
		lineageTag: 30d74c8c-b424-449d-bdfe-8b5256117344
		summarizeBy: none
		sourceColumn: capacity_gbps

	partition olt_info_clean = m
		mode: import
		source =
				let
				 Source = Csv.Document(File.Contents(DataRoot & "olt_info_clean.csv"),[Delimiter=",",Encoding=65001,QuoteStyle=QuoteStyle.Csv]),
				 Headers = Table.PromoteHeaders(Source,[PromoteAllScalars=true]),
				 Nulls = Table.ReplaceValue(Headers,"",null,Replacer.ReplaceValue,Table.ColumnNames(Headers)),
				 Typed = Table.TransformColumnTypes(Nulls,{{"olt_id", Int64.Type},{"olt_name", type text},{"capacity_gbps", Int64.Type}},"en-US")
				in Typed

