from pathlib import Path
import pandas as pd
import json,re,hashlib

R=Path(r'C:\Users\Admin\Documents\Network Congestion and Churn analysis')
B=R/'dashboard'/'OLT_Professional_Project'
names=['customers_clean','plans_clean','usage_logs_clean','customer_daily_metrics','olt_daily_metrics','olt_info_clean','complaints']
source={n:pd.read_csv(R/'data'/'clean'/(n+'.csv')) for n in names}
ready={n:pd.read_csv(B/'data'/(n+'.csv')) for n in names}
keys={'customers_clean':['customer_id'],'plans_clean':['plan_id'],'olt_info_clean':['olt_id'],'complaints':['complaint_id'],'customer_daily_metrics':['customer_id','log_date'],'olt_daily_metrics':['olt_id','log_date'],'usage_logs_clean':['customer_id','log_date']}
profiles={}
for n,d in source.items():
    profiles[n]={'rows':len(d),'columns':len(d.columns),'types':d.dtypes.astype(str).to_dict(),'missing':d.isna().sum().astype(int).to_dict(),'duplicate_rows':int(d.duplicated().sum()),'duplicate_keys':int(d.duplicated(keys[n]).sum()),'key':keys[n],'invalid_ids':{c:int((d[c].isna() | d[c].astype(str).str.strip().eq('')).sum()) for c in d if c.endswith('_id')},'invalid_dates':{c:int(pd.to_datetime(d[c],errors='coerce').isna().sum()) for c in d if c.endswith('_date')},'numeric_ranges':{c:{'min':float(d[c].min()),'max':float(d[c].max())} for c in d.select_dtypes('number')},'pii_columns':[c for c in d if re.search(r'(^name$|customer_name|phone|mobile|email|address|contact_number)',c,re.I)]}
    assert not profiles[n]['duplicate_keys']
    assert not profiles[n]['pii_columns']
    assert not any(profiles[n]['invalid_dates'].values())
relationships=[]
for child,c,parent,p in [('customers_clean','plan_id','plans_clean','plan_id'),('customers_clean','olt_id','olt_info_clean','olt_id'),('customer_daily_metrics','customer_id','customers_clean','customer_id'),('usage_logs_clean','customer_id','customers_clean','customer_id'),('complaints','customer_id','customers_clean','customer_id'),('olt_daily_metrics','olt_id','olt_info_clean','olt_id')]:
    missing=set(source[child][c])-set(source[parent][p]);assert not missing
    relationships.append({'child':child+'.'+c,'parent':parent+'.'+p,'orphans':len(missing)})
d=source['customer_daily_metrics'];c=source['customers_clean'];o=ready['olt_daily_metrics']
worst=d.groupby('customer_id').churn_risk_score.max()
risk_counts=pd.cut(worst,[-1,39,69,100],labels=['Low Risk','Medium Risk','High Risk']).value_counts().to_dict()
leak=((d.experience_score<50)&(d.complaint_count==0)).astype(int)
assert (leak==d.complaint_leakage_flag).all()
kpi={'Total Customers':int(c.customer_id.nunique()),'Total OLTs':int(source['olt_info_clean'].olt_id.nunique()),'High Congestion OLTs (average estimate)':int(o.loc[o.congestion_status=='High','olt_id'].nunique()),'High Risk Customers':int(d.loc[d.churn_risk_category=='High Risk','customer_id'].nunique()),'Avg Experience Score':float(d.experience_score.mean()),'Avg Congestion Ratio (average estimate)':float(o.congestion_ratio_percent.mean()),'Complaint Leakage':int(d.loc[d.complaint_leakage_flag==1,'customer_id'].nunique()),'Avg Downtime Minutes':float(d.downtime_minutes.mean()),'Avg Latency Ms':float(d.latency_ms.mean())}
qa={'source_profiles':profiles,'relationship_checks':relationships,'default_kpis':kpi,'exclusive_worst_risk_counts':{k:int(v) for k,v in risk_counts.items()},'leakage_rule_differences':0,'distinct_olt_ids':source['olt_info_clean'].olt_id.tolist(),'service_rows':len(c),'distinct_plan_ids':int(c.plan_id.nunique())}
(B/'data_quality.json').write_text(json.dumps(qa,indent=2))
lines=['# Data Quality Report','','Scope: seven approved clean CSVs; source files preserved.','', '| Table | Rows | Columns | Grain | Duplicate Keys |','|---|---:|---:|---|---:|']
for n,p in profiles.items():lines.append(f"| {n} | {p['rows']} | {p['columns']} | {' + '.join(p['key'])} | {p['duplicate_keys']} |")
lines+=['','## Confirmed Issues','', '- Invalid source utilization: source congestion_ratio_percent averages 32790.1191. The dashboard retains the prior rebuilt 24-hour utilization estimate of 0.0983313 (9.8%). It does not estimate peak congestion.','- 1,135 customer OLT assignments conflict with logged OLTs. Customer visuals use the assigned dimension OLT; network visuals use logged OLT. Operational comparisons need source-owner reconciliation.','- OLTs 11 and 12 have no network facts. Zero high-utilization OLTs applies only to observed OLTs.','- Only five dates are available. previous_7d_avg is a one-day-lagged expanding/rolling average, not a separate preceding seven-day period. Do not use it as a reliable seven-day usage-drop signal.','- Complaints are simulated according to existing project documentation. complaint_count is a customer-level all-period count repeated across dates, so leakage is not a historical as-of complaint measure.','- Daily risk categories overlap across dates. The professional distribution charts now assign each customer to their highest observed risk within the selected context. Default counts are 851 low, 424 medium, 5 high, totaling 1,280.','- Churn risk is a rule-based proxy; downtime and latency are inputs to its score. Diagnostic associations are descriptive, not causal validation or independent prediction.','','## Validated Checks','','No duplicate business keys, blank analytical IDs, invalid dates, or orphan parent keys were found. Experience scores and risk scores remain within 0-100. Existing leakage flags match the supplied check with zero differences and zero cases.','','## Default KPIs','',*['- '+k+': '+str(v) for k,v in kpi.items()],'','Complete column profiles, missing counts, numeric ranges and key checks are in dashboard/OLT_Professional_Project/data_quality.json.']
(R/'DATA_QUALITY_REPORT.md').write_text('\n'.join(lines),encoding='utf-8')
(R/'PRIVACY_AUDIT.md').write_text('# Privacy Audit\n\nOnly the seven approved clean CSVs and the copied TMDL model were used. Column screening found no direct names, phone numbers, emails, addresses or contact fields. Customer keys are pseudonymous Customer_ identifiers. OLT names are network labels, not personal names. Raw CSV/XLSX data was not imported. Area-level geography is retained. Pseudonymization is not a guarantee against re-identification. Screenshots are exported from the report canvas, excluding application account details.\n',encoding='utf-8')
(R/'TRANSFORMATION_LOG.md').write_text('# Transformation Log\n\nThe original PBIX remains the rollback file. A Professional PBIX working copy was created in the same dashboard folder. The valid prior TMDL model and transformed CSVs were copied to OLT_Professional_Project. Existing source CSVs and the previous one-page PBIP remain unchanged.\n\nThe Professional report adds two distinct light-theme pages, synchronized slicers, page navigation, reset bookmarks, diagnostic measures, conditional utilization colors and a distinct highest-observed-risk distribution. Existing core measures and relationships are preserved. The copied CSV query paths point to the Professional project. No synthetic observations were added. Daily average utilization retains the prior corrected formula; absent peak telemetry is explicitly disclosed.\n',encoding='utf-8')
modeltext=(B/'OLT.SemanticModel'/'definition'/'relationships.tmdl').read_text()
(R/'dashboard'/'Data_Model.md').write_text('# Power BI Data Model\n\nThe Professional report reuses the established TMDL model. All core relationships are active, single direction, one-to-many. DateTable is a marked time table with a unique date column, Year, Month Number, Month (sorted by Month Number), and Year Month. Dates cover the supplied five-day window; extend the date query when new data arrives.\n\n```mermaid\nerDiagram\n plans_clean ||--o{ customers_clean : plan_id\n olt_info_clean ||--o{ customers_clean : assigned_olt\n olt_info_clean ||--o{ olt_daily_metrics : logged_olt\n customers_clean ||--o{ customer_daily_metrics : customer_id\n customers_clean ||--o{ usage_logs_clean : customer_id\n customers_clean ||--o{ complaints : customer_id\n DateTable ||--o{ customer_daily_metrics : date\n DateTable ||--o{ olt_daily_metrics : date\n DateTable ||--o{ usage_logs_clean : date\n DateTable ||--o{ complaints : date\n```\n\nCustomers, plans and OLTs are dimensions. Usage and customer metrics have customer-date grain; OLT metrics have OLT-date grain; complaints have event grain. No direct customer-fact-to-network-fact relationship is added. Risk filters do not artificially restrict network facts. Total Customers remains the selected dimension population.\n\nUsage logs is related and available through Total Usage GB, but no redundant usage chart is added: daily metrics already contains the same usage, and five days cannot support the prior seven-day-drop interpretation.\n\n## Executable Relationships\n```tmdl\n'+modeltext+'\n```\n',encoding='utf-8')
measures=(B/'OLT.SemanticModel'/'definition'/'tables'/'_Measures.tmdl').read_text()
blocks=re.findall(r"\tmeasure '([^']+)' = (.*?)(?=\n\t(?:measure|column|partition) |\Z)",measures,re.S)
dax=['# DAX Measures','','Core measures are preserved. The following definitions are loaded in the Professional semantic model.']
for n,b in blocks:
    expression=b.split('\n\t\t')[0].strip();dax+=['','## '+n,'','```dax',n+' = '+expression,'```']
dax+=['','Worst Risk Customers prevents double counting across daily risk categories. It evaluates each customer\'s maximum risk score within the selected dates and slicer context. Network metrics use daily average utilization; they do not measure peak congestion.']
(R/'dashboard'/'DAX_Measures.md').write_text('\n'.join(dax),encoding='utf-8')
print(json.dumps(kpi,indent=2))
